
import type { FC, SVGProps } from 'react';
import { VirusTotalLogo, AbuseIPDBLogo, SecurityTrailsLogo, GreyNoiseLogo, ShodanLogo, AlienVaultLogo, IPQualityScoreLogo, CiscoTalosLogo, IBMXForceLogo, GoogleSafeBrowsingLogo, APIVoidLogo, WhoisXMLLogo, SpamhausLogo, NeutrinoAPILogo, ThreatMinerLogo, FraudGuardLogo, ZscalerLogo, WebrootLogo, RiskIQLogo } from '@/components/logos';
import type { Service } from './types';

export const services: Service[] = [
  {
    id: 'virustotal',
    name: 'VirusTotal',
    alias: 'VT',
    icon: VirusTotalLogo,
    description: 'Reputation and analysis of files, domains, IPs, and URLs, with detailed stats.',
    placeholder: 'Enter a VT resource (domain, IP, URL)',
    inputType: 'resource',
    documentationUrl: 'https://developers.virustotal.com/reference/overview',
    pricing: 'Free',
    requestLimit: 500,
  },
  {
    id: 'abuseipdb',
    name: 'AbuseIPDB',
    alias: 'AIPDB',
    icon: AbuseIPDBLogo,
    description: 'IP abuse confidence score, report counts, and network context. IP addresses only.',
    placeholder: 'Enter an AIPDB resource (IP address)',
    inputType: 'ipAddress',
    documentationUrl: 'https://docs.abuseipdb.com/',
    pricing: 'Free',
    requestLimit: 1000,
  },
  {
    id: 'securitytrails',
    name: 'SecurityTrails',
    alias: 'ST',
    icon: SecurityTrailsLogo,
    description: 'Primary WHOIS provider with full registrant data, plus DNS and infrastructure intel.',
    placeholder: 'Enter an ST resource (domain or IP)',
    inputType: 'resource',
    documentationUrl: 'https://docs.securitytrails.com/docs',
    pricing: 'Free',
    requestLimit: 50,
  },
  {
    id: 'greynoise',
    name: 'GreyNoise',
    alias: 'GN',
    icon: GreyNoiseLogo,
    description: 'Internet noise and mass-scan intelligence. Excludes WHOIS. IP addresses only.',
    placeholder: 'Enter a GN resource (IP address)',
    inputType: 'ipAddress',
    documentationUrl: 'https://docs.greynoise.io/',
    pricing: 'Free',
    requestLimit: 50,
  },
  {
    id: 'shodan',
    name: 'Shodan',
    alias: 'Shodan',
    icon: ShodanLogo,
    description: 'Search for internet-connected devices, open ports, services, and vulnerabilities.',
    placeholder: 'Enter a Shodan resource (IP or query)',
    inputType: 'query',
    documentationUrl: 'https://developer.shodan.io/',
    pricing: 'Free',
    requestLimit: 100,
  },
  {
    id: 'alienvault',
    name: 'AlienVault OTX',
    alias: 'OTX',
    icon: AlienVaultLogo,
    description: 'WHOIS data combined with threat pulses, reputation, and passive DNS.',
    placeholder: 'Enter an OTX resource (IP, domain, hash)',
    inputType: 'resource',
    documentationUrl: 'https://otx.alienvault.com/api',
    pricing: 'Free',
    requestLimit: 2000,
  },
  {
    id: 'ipqualityscore',
    name: 'IPQualityScore',
    alias: 'IPQS',
    icon: IPQualityScoreLogo,
    description: 'Fraud detection, IP scoring, and proxy/VPN detection. IP addresses only.',
    placeholder: 'Enter an IPQS resource (IP address)',
    inputType: 'ipAddress',
    documentationUrl: 'https://www.ipqualityscore.com/documentation/overview',
    pricing: 'Free',
    requestLimit: 5000,
  },
  {
    id: 'ciscotalos',
    name: 'Cisco Talos',
    alias: 'Talos',
    icon: CiscoTalosLogo,
    description: 'Comprehensive threat intelligence from Cisco Talos. IP and domain reputation.',
    placeholder: 'Enter a Talos resource (IP, domain)',
    inputType: 'resource',
    documentationUrl: 'https://talosintelligence.com/reputation_center/lookup',
    pricing: 'Free',
    requestLimit: null,
  },
  {
    id: 'xforce',
    name: 'IBM X-Force',
    alias: 'X-Force',
    icon: IBMXForceLogo,
    description: 'Threat intelligence on IPs, URLs, and vulnerabilities from IBM X-Force Exchange.',
    placeholder: 'Enter an X-Force resource (IP, URL, hash)',
    inputType: 'resource',
    documentationUrl: 'https://api.xforce.ibmcloud.com/docs/',
    pricing: 'Free',
    requestLimit: 5000,
  },
  {
    id: 'googlesafebrowsing',
    name: 'Google Safe Browsing',
    alias: 'GSB',
    icon: GoogleSafeBrowsingLogo,
    description: 'Detects malicious URLs, domains, and IPs (phishing, malware).',
    placeholder: 'Enter a URL, domain, or IP',
    inputType: 'resource',
    documentationUrl: 'https://developers.google.com/safe-browsing/v4/lookup-api',
    pricing: 'Free',
    requestLimit: 10000,
  },
  {
    id: 'apivoid',
    name: 'APIVoid',
    alias: 'APIVoid',
    icon: APIVoidLogo,
    description: 'Aggregated reputation and blacklist checks for IPs, domains, and URLs.',
    placeholder: 'Enter an IP, domain, or URL',
    inputType: 'resource',
    documentationUrl: 'https://www.apivoid.com/api/',
    pricing: 'Free',
    requestLimit: 100,
  },
  {
    id: 'whoisxml',
    name: 'WhoisXML API',
    alias: 'WXML',
    icon: WhoisXMLLogo,
    description: 'Authoritative WHOIS and RDAP provider for domains, IPs, and ASNs.',
    placeholder: 'Enter a domain, IP, or ASN',
    inputType: 'resource',
    documentationUrl: 'https://www.whoisxmlapi.com/documentation/',
    pricing: 'Free',
    requestLimit: 500,
  },
  {
    id: 'spamhaus',
    name: 'Spamhaus',
    alias: 'Spamhaus',
    icon: SpamhausLogo,
    description: 'Authoritative spam and abuse blocklists for IPs and domains.',
    placeholder: 'Enter an IP or domain',
    inputType: 'resource',
    documentationUrl: 'https://www.spamhaus.org/documentation/',
    pricing: 'Free',
    requestLimit: null,
  },
  {
    id: 'neutrino',
    name: 'Neutrino API',
    alias: 'Neutrino',
    icon: NeutrinoAPILogo,
    description: 'Fraud, abuse, and IP intelligence. Detects proxies, VPNs, and TOR.',
    placeholder: 'Enter an IP address',
    inputType: 'ipAddress',
    documentationUrl: 'https://www.neutrinoapi.com/api/ip-probe/',
    pricing: 'Free',
    requestLimit: 25,
  },
  {
    id: 'threatminer',
    name: 'ThreatMiner',
    alias: 'TM',
    icon: ThreatMinerLogo,
    description: 'Passive OSINT aggregation for IPs, domains, and hashes.',
    placeholder: 'Enter an IP, domain, or hash',
    inputType: 'resource',
    documentationUrl: 'https://www.threatminer.org/api.php',
    pricing: 'Free',
    requestLimit: null,
  },
  {
    id: 'fraudguard',
    name: 'FraudGuard',
    alias: 'FG',
    icon: FraudGuardLogo,
    description: 'IP fraud and abuse scoring. Detects proxies, TOR, and VPNs.',
    placeholder: 'Enter an IP address',
    inputType: 'ipAddress',
    documentationUrl: 'https://fraudguard.io/docs',
    pricing: 'Paid',
    requestLimit: null,
  },
  {
    id: 'zscaler',
    name: 'Zscaler ThreatLabZ',
    alias: 'Zscaler',
    icon: ZscalerLogo,
    description: 'Enterprise-grade URL and IP reputation and categorization.',
    placeholder: 'Enter a URL, domain, or IP',
    inputType: 'resource',
    documentationUrl: 'https://help.zscaler.com/zia/api',
    pricing: 'Paid',
    requestLimit: null,
  },
  {
    id: 'webroot',
    name: 'Webroot BrightCloud',
    alias: 'Webroot',
    icon: WebrootLogo,
    description: 'Commercial reputation and categorization for IPs, domains, and URLs.',
    placeholder: 'Enter an IP, domain, or URL',
    inputType: 'resource',
    documentationUrl: 'https://www.brightcloud.com/support/api-documentation.php',
    pricing: 'Paid',
    requestLimit: null,
  },
  {
    id: 'riskiq',
    name: 'RiskIQ PassiveTotal',
    alias: 'RiskIQ',
    icon: RiskIQLogo,
    description: 'Advanced passive DNS and infrastructure intelligence.',
    placeholder: 'Enter an IP, domain, or ASN',
    inputType: 'resource',
    documentationUrl: 'https://community.riskiq.com/docs',
    pricing: 'Free',
    requestLimit: 15,
  },
];
